import { describe, expect, it } from 'vitest'
import { buildCanvasOperationProjection } from './canvasOperationProjection'
import type { CanvasEdge, CanvasNode } from './canvas.types'

function node(id: string, type: CanvasNode['type']): CanvasNode {
  return {
    id,
    projectId: 'project-1',
    boardId: 'board-1',
    userId: 1,
    type,
    x: 0,
    y: 0,
    width: 560,
    height: 360,
    rotation: 0,
    zIndex: 1,
    locked: false,
    hidden: false,
    data: {},
    createdAt: '2026-07-10T00:00:00.000Z',
    updatedAt: '2026-07-10T00:00:00.000Z',
  }
}

function edge(
  id: string,
  sourceNodeId: string,
  targetNodeId: string,
  type: CanvasEdge['type'],
): CanvasEdge {
  return {
    id,
    projectId: 'project-1',
    boardId: 'board-1',
    userId: 1,
    sourceNodeId,
    targetNodeId,
    type,
    metadata: {},
    createdAt: '2026-07-10T00:00:00.000Z',
  }
}

describe('canvas operation projection', () => {
  it('embeds generated outputs and folds downstream edges back to the operation node', () => {
    const nodes = [
      node('extract-characters', 'text_generate'),
      node('character-output', 'text'),
      node('next-operation', 'text_to_image'),
      node('manual-note', 'text'),
    ]
    const edges = [
      edge('generated', 'extract-characters', 'character-output', 'generated'),
      edge('downstream', 'character-output', 'next-operation', 'used_as_input'),
      edge('reference', 'manual-note', 'character-output', 'references'),
    ]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.visibleNodes.map((item) => item.id)).toEqual([
      'extract-characters',
      'next-operation',
      'manual-note',
    ])
    expect(projection.visibleEdges).toEqual([
      expect.objectContaining({
        id: 'downstream',
        sourceNodeId: 'extract-characters',
        targetNodeId: 'next-operation',
      }),
      expect.objectContaining({
        id: 'reference',
        sourceNodeId: 'manual-note',
        targetNodeId: 'extract-characters',
      }),
    ])
  })

  it('keeps resource nodes visible when they are not generated by an operation node', () => {
    const nodes = [node('manual-source', 'text'), node('resource-output', 'text')]
    const edges = [edge('legacy-generated', 'manual-source', 'resource-output', 'generated')]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.visibleNodes).toHaveLength(2)
    expect(projection.visibleEdges).toHaveLength(1)
  })

  it('keeps a video workbench visible when a legacy manual edge was stored as generated', () => {
    const operation = node('source-operation', 'text_to_video')
    const workbench = node('workbench', 'text')
    workbench.data.subtype = 'video_workbench'

    const projection = buildCanvasOperationProjection(
      [operation, workbench],
      [edge('legacy-manual-generated', operation.id, workbench.id, 'generated')],
    )

    expect(projection.visibleNodes.map((item) => item.id)).toEqual([operation.id, workbench.id])
    expect(projection.embeddedOutputNodeIds).toEqual(new Set())
  })

  it('shows generated outputs after they are materialized inside a real group', () => {
    const operation = node('generate-frames', 'text_to_image')
    const group = node('frame-group', 'group')
    const first = { ...node('frame-a', 'image'), parentNodeId: group.id }
    const second = { ...node('frame-b', 'image'), parentNodeId: group.id }
    const nodes = [operation, group, first, second]
    const edges = [
      edge('generated-a', operation.id, first.id, 'generated'),
      edge('generated-b', operation.id, second.id, 'generated'),
      edge('contains-a', group.id, first.id, 'group_contains'),
      edge('contains-b', group.id, second.id, 'group_contains'),
    ]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.visibleNodes.map((item) => item.id)).toEqual([
      operation.id,
      group.id,
      first.id,
      second.id,
    ])
    expect(projection.embeddedOutputNodeIds).toEqual(new Set())
    expect(projection.visibleEdges.map((item) => item.id)).toEqual(['contains-a', 'contains-b'])
  })
})
