import { describe, expect, it } from 'vitest'
import { buildCanvasOperationProjection } from './canvasOperationProjection'
import type { CanvasEdge, CanvasNode } from './canvas.types'

function node(id: string, type: CanvasNode['type']): CanvasNode {
  return {
    id,
    projectId: 'project-1',
    boardId: 'board-1',
    userId: 1,
    type,
    x: 0,
    y: 0,
    width: 560,
    height: 360,
    rotation: 0,
    zIndex: 1,
    locked: false,
    hidden: false,
    data: {},
    createdAt: '2026-07-10T00:00:00.000Z',
    updatedAt: '2026-07-10T00:00:00.000Z',
  }
}

function edge(
  id: string,
  sourceNodeId: string,
  targetNodeId: string,
  type: CanvasEdge['type'],
): CanvasEdge {
  return {
    id,
    projectId: 'project-1',
    boardId: 'board-1',
    userId: 1,
    sourceNodeId,
    targetNodeId,
    type,
    metadata: {},
    createdAt: '2026-07-10T00:00:00.000Z',
  }
}

describe('canvas operation projection', () => {
  it('embeds generated outputs and folds downstream edges back to the operation node', () => {
    const nodes = [
      node('extract-characters', 'text_generate'),
      node('character-output', 'text'),
      node('next-operation', 'text_to_image'),
      node('manual-note', 'text'),
    ]
    const edges = [
      edge('generated', 'extract-characters', 'character-output', 'generated'),
      edge('downstream', 'character-output', 'next-operation', 'used_as_input'),
      edge('reference', 'manual-note', 'character-output', 'references'),
    ]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.visibleNodes.map((item) => item.id)).toEqual([
      'extract-characters',
      'next-operation',
      'manual-note',
    ])
    expect(projection.visibleEdges).toEqual([
      expect.objectContaining({
        id: 'downstream',
        sourceNodeId: 'extract-characters',
        targetNodeId: 'next-operation',
      }),
      expect.objectContaining({
        id: 'reference',
        sourceNodeId: 'manual-note',
        targetNodeId: 'extract-characters',
      }),
    ])
  })

  it('keeps resource nodes visible when they are not generated by an operation node', () => {
    const nodes = [node('manual-source', 'text'), node('resource-output', 'text')]
    const edges = [edge('legacy-generated', 'manual-source', 'resource-output', 'generated')]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.visibleNodes).toHaveLength(2)
    expect(projection.visibleEdges).toHaveLength(1)
  })

  it('dedupes overlapping edges when multiple outputs from one operation feed the same downstream', () => {
    const nodes = [
      node('extract-characters', 'text_generate'),
      node('character-a', 'text'),
      node('character-b', 'text'),
      node('downstream', 'text_to_image'),
    ]
    const edges = [
      edge('gen-a', 'extract-characters', 'character-a', 'generated'),
      edge('gen-b', 'extract-characters', 'character-b', 'generated'),
      edge('use-a', 'character-a', 'downstream', 'used_as_input'),
      edge('use-b', 'character-b', 'downstream', 'used_as_input'),
    ]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.visibleNodes.map((item) => item.id)).toEqual([
      'extract-characters',
      'downstream',
    ])
    expect(projection.visibleEdges).toEqual([
      expect.objectContaining({
        sourceNodeId: 'extract-characters',
        targetNodeId: 'downstream',
        type: 'used_as_input',
      }),
    ])
  })

  it('fans one output out to multiple downstream operations as separate edges', () => {
    const nodes = [
      node('generate-image', 'text_to_image'),
      node('image-output', 'image'),
      node('to-video', 'image_to_video'),
      node('upscale', 'image_to_image'),
    ]
    const edges = [
      edge('gen', 'generate-image', 'image-output', 'generated'),
      edge('to-video-link', 'image-output', 'to-video', 'used_as_input'),
      edge('upscale-link', 'image-output', 'upscale', 'used_as_input'),
    ]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.visibleNodes.map((item) => item.id)).toEqual([
      'generate-image',
      'to-video',
      'upscale',
    ])
    expect(projection.visibleEdges.map((item) => item.targetNodeId)).toEqual([
      'to-video',
      'upscale',
    ])
  })

  it('keeps the first producer when an output is generated by multiple operations', () => {
    const nodes = [
      node('op-a', 'text_to_image'),
      node('op-b', 'image_to_image'),
      node('shared-output', 'image'),
      node('downstream', 'image_to_video'),
    ]
    const edges = [
      edge('gen-a', 'op-a', 'shared-output', 'generated'),
      edge('gen-b', 'op-b', 'shared-output', 'generated'),
      edge('use', 'shared-output', 'downstream', 'used_as_input'),
    ]

    const projection = buildCanvasOperationProjection(nodes, edges)

    expect(projection.producerByOutputNodeId.get('shared-output')).toBe('op-a')
    expect(projection.visibleEdges).toEqual([
      expect.objectContaining({
        sourceNodeId: 'op-a',
        targetNodeId: 'downstream',
      }),
    ])
  })
})
