/**
 * @spark/storage — Spark Agent 存储层
 *
 * 职责：
 *   - SQLite 数据库连接管理（better-sqlite3 + WAL）
 *   - Migration 管理（版本号递增策略）
 *   - Repository 模式的基类
 *   - 各领域 Repository 的导出入口
 *
 * 约束（ADR-002）：
 *   - 本包是唯一合法的数据库访问入口
 *   - 所有 SQL 通过 prepared statement 执行
 *   - 数据库文件路径由调用方（Electron 主进程）提供
 *   - API Key 不存储在 SQLite 中，只存储 keychain_ref
 */

// 数据库核心
export { SparkDatabase, createDatabase } from './database.js'
export type { SqliteDatabase } from './database.js'

// CJK 逐字预分词（memory_fts 写入/查询两侧共用，禁止各自实现）
export { segmentCjk, buildFtsMatchQuery } from './segment-cjk.js'

// Repository（向后兼容）
export { BaseRepository } from './repository.js'
export { RoomLedgerService, RoomLedgerConflictError } from './room-ledger.service.js'
export type { RoomLedgerMutationInput } from './room-ledger.service.js'
export {
  TeamHandoffService,
  TeamHandoffConflictError,
  TEAM_HANDOFF_MAX_PER_DISCUSSION,
} from './team-handoff.service.js'
export type {
  TeamHandoffRecord,
  TeamHandoffEvent,
  TeamHandoffStatus,
  TeamHandoffSensitivity,
  TeamHandoffOperation,
} from './team-handoff.service.js'
export {
  SteeringGateService,
  SteeringGateConflictError,
  SteeringGateBlockedError,
  STEERING_GATE_MAX_PER_DISCUSSION,
} from './steering-gate.service.js'
export type {
  SteeringGateRecord,
  SteeringGateEvent,
  SteeringGateStatus,
  SteeringGateImpact,
  SteeringTargetType,
  SteeringGateOperation,
  SteeringCapability,
} from './steering-gate.service.js'
export { TaskGraphService, TaskGraphConflictError } from './task-graph.service.js'
export type {
  TaskGraphScope,
  TaskGraphEvent,
  TaskGraphCapability,
  TaskEdgeRecord,
} from './task-graph.service.js'
export {
  DeliberationService,
  DeliberationConflictError,
  DELIBERATION_MAX_PER_DISCUSSION,
} from './deliberation.service.js'
export type { DeliberationScope, DeliberationLedgerWriter } from './deliberation.service.js'
export { EvidenceCostService, EvidenceCostConflictError } from './evidence-cost.service.js'
export type { EvidenceCostScope, EvidenceCostCapability } from './evidence-cost.service.js'
export { ReplayPlaybookService, ReplayPlaybookConflictError } from './replay-playbook.service.js'
export type { ReplayScope, ReplayCapability } from './replay-playbook.service.js'
export type {
  RoomLedgerRecord,
  RoomLedgerStatus,
  RoomLedgerAuthority,
  RoomLedgerOperation,
  RoomLedgerEvent,
} from './repositories/room-ledger.repository.js'

// 领域 Repository
export {
  SessionRepository,
  SessionCollaborationRepository,
  WorkspaceRepository,
  EventRepository,
  TurnRequestRepository,
  ConnectorConnectionRepository,
  ConnectorAccountRepository,
  PluginRuntimeAuditRepository,
  ProviderProfileRepository,
  RulesRepository,
  PermissionProfileRepository,
  ModelProfileRepository,
  MediaModelManifestRepository,
  MediaGenerationTaskRepository,
  McpServerRepository,
  SkillRepository,
  SkillRegistryRepository,
  PluginRepository,
  SettingsRepository,
  UsageLedgerRepository,
  ContextPreferenceRepository,
  SessionSummaryRepository,
  AgentRepository,
  WorkflowRepository,
  WorkflowRunRepository,
  TeamDispatchRepository,
  TeamDiscussionRepository,
  DEFAULT_MAX_DISCUSSION_ROUNDS,
  HARD_MAX_DISCUSSION_ROUNDS,
  DEFAULT_THREAD_TOKEN_BUDGET,
  TeamDefinitionRepository,
  ScheduledTaskRepository,
  TaskExecutionRepository,
  MemoryRepository,
  MemorySearchRepository,
  upsertFtsRow,
  deleteFtsRow,
  ftsTableExists,
  MemoryEntityRepository,
  normalizeEntityName,
  GoalRepository,
  CanvasProjectRepository,
  CanvasSnapshotRepository,
  CanvasWorkflowRepository,
  CanvasWorkflowRunRepository,
  CanvasWorkflowVersionRepository,
  ApplicationSnapshotRepository,
  ComputerSessionRepository,
  ComputerActionRepository,
  ComputerActivityEventRepository,
  ComputerApprovalRepository,
  ComputerVerificationRepository,
  ComputerActuatorLeaseRepository,
  SubAppRepository,
  SubAppConflictError,
  SubAppDataConflictError,
  SubAppDataValidationError,
  SubAppNotFoundError,
  SubAppReleaseNotFoundError,
  SubAppStateError,
  CustomToolRepository,
} from './repositories/index.js'

export type {
  SessionRow,
  SessionLineageRow,
  SessionReferenceRow,
  SessionReferenceAuditRow,
  SessionReferenceCandidate,
  SessionReferenceView,
  SessionForkResult,
  ReferencedSessionTurn,
  ReferencedSessionReadResult,
  ReferencedSessionSearchHit,
  CreateSessionParams,
  ListSessionsParams,
  WorkspaceRow,
  CreateWorkspaceParams,
  WorktreeMeta,
  AgentEventRow,
  QueryEventsParams,
  InsertEventParams,
  TurnRequestRow,
  TurnRequestStatus,
  ConnectorConnectionRow,
  CreateConnectorConnectionParams,
  UpdateConnectorConnectionParams,
  ConnectorAccountRow,
  UpsertConnectorAccountParams,
  UpdateConnectorAccountParams,
  PluginRuntimeAuditParams,
  ProviderProfileRow,
  CreateProviderParams,
  RuleRow,
  CreateRuleParams,
  UpdateRuleParams,
  ListRulesParams,
  PermissionDecisionRow,
  PermissionProfileRow,
  PermissionRuleRow,
  ModelProfileRow,
  MediaModelManifestRow,
  MediaProviderModelRow,
  UpsertMediaModelManifestParams,
  UpsertMediaProviderModelParams,
  MediaGenerationTaskRow,
  MediaGenerationTaskStatus,
  CreateMediaGenerationTaskParams,
  UpdateMediaGenerationTaskParams,
  ListMediaGenerationTasksParams,
  McpServerRow,
  SkillRow,
  SkillRegistryRow,
  PluginPermissionRow,
  PluginRegistryRow,
  PluginResourceRow,
  PluginRow,
  PluginSource,
  PluginState,
  PluginTrust,
  SettingsRow,
  UsageLedgerRow,
  RecordUsageParams,
  UsageSummary,
  ModelUsageGroup,
  DailyUsageGroup,
  ContextPreferenceRow,
  UpsertContextPreferenceParams,
  ListContextPreferencesParams,
  SessionSummaryRow,
  CreateSessionSummaryParams,
  AgentConfig,
  AgentItem,
  AgentRow,
  CreateAgentParams,
  UpdateAgentParams,
  CreateWorkflowParams,
  UpdateWorkflowParams,
  WorkflowItem,
  WorkflowRow,
  WorkflowStatus,
  CreateWorkflowRunParams,
  UpdateWorkflowRunSnapshotParams,
  WorkflowRunRow,
  WorkflowRunStatus,
  TeamDispatchRow,
  TeamDispatchState,
  CreateTeamDispatchParams,
  UpdateTeamDispatchParams,
  AgentTeamRow,
  AgentTeamItem,
  CreateAgentTeamParams,
  UpdateAgentTeamParams,
  ListAgentTeamsParams,
  ScheduledTaskRow,
  CreateScheduledTaskParams,
  UpdateScheduledTaskParams,
  ScheduledTaskFilter,
  TaskExecutionRow,
  CreateTaskExecutionParams,
  ExecutionQueryOptions,
  ExecutionStats,
  MemoryEntryRow,
  MemoryEntryInsert,
  MemoryScopeFilter,
  FtsSearchOptions,
  FtsSearchHit,
  VecSearchHit,
  SessionGoal,
  GoalBudget,
  GoalValidation,
  GoalProgressEntry,
  GoalStatus,
  GoalMode,
  CanvasProjectRow,
  CanvasSnapshotRow,
  UpsertCanvasProjectParams,
  CanvasWorkflowRow,
  CanvasWorkflowItem,
  CanvasWorkflowScope,
  CanvasWorkflowStatus,
  CreateCanvasWorkflowParams,
  UpdateCanvasWorkflowParams,
  ListCanvasWorkflowsParams,
  DuplicateCanvasWorkflowParams,
  CanvasWorkflowVersionRow,
  CreateCanvasWorkflowVersionParams,
  CanvasWorkflowRunStatus,
  CanvasWorkflowRunStepStatus,
  CanvasWorkflowRunRow,
  CanvasWorkflowRunStepRow,
  CreateCanvasWorkflowRunParams,
  CreateCanvasWorkflowRunStepParams,
  ListCanvasWorkflowRunsParams,
  UpdateCanvasWorkflowRunParams,
  UpdateCanvasWorkflowRunStepParams,
  AppendMessageParams,
  TeamThreadMessageKind,
  TeamThreadMessageDelivery,
  TeamThreadMessageRow,
  TeamDiscussionRow,
  ApplicationSnapshotRow,
  SnapshotBlobRow,
  SnapshotBlobKind,
  ApplicationSnapshotKind,
  SnapshotRetentionMode,
  CreateSnapshotBlobParams,
  CreateApplicationSnapshotParams,
  CreateApplicationSnapshotWithBlobsParams,
  ComputerSessionRow,
  CreateComputerSessionParams,
  StoredComputerEnvironment,
  StoredComputerSessionStatus,
  ComputerActionRow,
  CreateComputerActionParams,
  StoredComputerActionStatus,
  ComputerActivityEventRow,
  CreateComputerActivityEventParams,
  ComputerApprovalRow,
  CreatePendingComputerApprovalParams,
  ComputerVerificationRow,
  ComputerActuatorLeaseRow,
  CreateSubAppParams,
  SubAppDataRow,
  SubAppListPage,
  SubAppReleaseRow,
  SubAppRow,
  CustomToolRow,
  CustomToolSpecEnvelope,
} from './repositories/index.js'
