/**
 * 文档主题索引 —— 所有文档主题的元信息集中在这里。
 *
 * 主题正文（真正可读的内容）按主题拆到 `docs-pages/<slug>.tsx`，
 * 由 docs-page-registry.ts 统一注册，以便构建期预渲染完整正文。
 *
 * 改主题时只需：
 *   1) 在 docs.ts 的 `docsTopics` 加/删一条
 *   2) 在 docs-pages/ 下新增/删除对应 .tsx 文件
 *   3) 在 docs-page-registry.ts 加/删对应的同步注册项
 */

export type DocCategory =
  | 'getting-started' // 入门 / 安装
  | 'code' // 代码开发
  | 'team' // 团队 Agent
  | 'canvas' // 无限画布
  | 'content' // 内容与媒体生产
  | 'provider' // 模型 / 多媒体 Provider
  | 'mcp' // MCP / Skills / 工具
  | 'governance' // 权限 / 治理
  | 'release' // 发布 / 更新

export interface DocsTopicMeta {
  /** URL 段：/docs/<slug> */
  slug: string
  /** 浏览器标签与 hero 区显示的标题 */
  title: string
  /** 一句话说明，用于卡片 / meta description / 搜索结果 */
  description: string
  /** 卡片副标题（在 DocsPage 主题导航里展示的细节） */
  detail: string
  /** 主题所属分类，决定 DocsPage 上的分组 */
  category: DocCategory
  /** 主题级别标签，便于筛选 */
  level: 'beginner' | 'intermediate' | 'advanced'
  /** 用于全文检索的关键词（标题 / 描述之外再补充） */
  keywords: string[]
  /** 预计阅读时长（分钟），给读者一个心理预期 */
  readTime: number
  /** 文档最近一次核对 / 更新日期，ISO YYYY-MM-DD */
  updatedAt: string
  /** 在 GitHub 仓库中的原始 md 路径，给想看完整版本的用户跳转 */
  githubSource?: string
  /** 同主题里互相跳转的相关主题 slug */
  relatedSlugs?: string[]
  /** lucide-react 图标名（在 DocsPage 卡片上展示） */
  icon:
    | 'Sparkles'
    | 'TerminalSquare'
    | 'Users'
    | 'LayoutGrid'
    | 'FileText'
    | 'ImageIcon'
    | 'Search'
    | 'Globe'
    | 'Cable'
    | 'RefreshCw'
    | 'Webhook'
    | 'PackageOpen'
    | 'AppWindow'
    | 'Boxes'
    | 'ShieldCheck'
    | 'KeyRound'
    | 'Database'
    | 'Terminal'
}

export const docsTopics: DocsTopicMeta[] = [
  {
    slug: 'quick-start',
    title: '快速开始',
    detail: '从安装到完成第一个真实任务',
    description:
      'Spark Work 快速开始指南：下载适合你系统的安装包、完成首次启动、接入模型服务、创建第一个 Agent 并完成第一个任务。',
    category: 'getting-started',
    level: 'beginner',
    keywords: ['安装', '下载', '首次启动', '快速开始', 'quick start', 'getting started'],
    readTime: 5,
    updatedAt: '2026-07-05',
    icon: 'Sparkles',
    relatedSlugs: ['agents-workflows', 'desktop-guide', 'auto-update'],
  },
  {
    slug: 'code-development',
    title: '代码开发',
    detail: 'Worktree、终端、审查与补丁',
    description:
      '在 Spark Work 中做真实的代码开发：打开项目、选择分支、用 Git Worktree 隔离、在终端跑验证、逐文件审查 AI 改动并生成 Pull Request。',
    category: 'code',
    level: 'intermediate',
    keywords: ['代码', 'worktree', '终端', '审查', 'PR', 'code development', 'review'],
    readTime: 7,
    updatedAt: '2026-06-29',
    icon: 'TerminalSquare',
    relatedSlugs: ['agents-workflows', 'team-mode', 'remote-connections'],
  },
  {
    slug: 'agents-workflows',
    title: 'Agent 工作流',
    detail: 'Agent 配置、真实执行工作流、工具选择与上下文',
    description:
      'Spark Work 中 Agent 的工作机制：默认 Agent、Provider/Model/Skill/Rule 配置、全局已启用 MCP 自动挂载、可真实执行的 Workflow Graph、workflow_run、运行快照与 [Runtime Rules] 段。',
    category: 'team',
    level: 'intermediate',
    keywords: ['Agent', '工作流', 'workflow', 'skills', 'rules', 'MCP', 'spark_platform'],
    readTime: 10,
    updatedAt: '2026-07-16',
    icon: 'Users',
    githubSource: 'docs/agents-workflows.md',
    relatedSlugs: ['team-mode', 'mcp-skills', 'web-search', 'browser-automation'],
  },
  {
    slug: 'team-mode',
    title: '团队模式',
    detail: 'Host / Member 调度、事件流与预算',
    description:
      'Spark Work 团队模式（Team Mode）：Host Agent 把子任务分派给多个 Member Agent，每个 Member 有独立模型/工具/Skills，事件流式展示分派、回复与完成。',
    category: 'team',
    level: 'advanced',
    keywords: ['团队', '多 Agent', 'host', 'member', 'dispatch', 'agent_dispatch'],
    readTime: 9,
    updatedAt: '2026-07-16',
    icon: 'Boxes',
    githubSource: 'docs/agents-workflows.md#team-mode-agent-to-agent',
    relatedSlugs: ['agents-workflows', 'governance'],
  },
  {
    slug: 'canvas-mvp',
    title: '无限画布',
    detail: '节点、资产、任务、影视创作与生成链路',
    description:
      'Spark Work 无限画布（Infinite Canvas）能力全景：项目管理、节点类型、AI 操作、任务队列、生成结果节点、lineage 边、资产中心、媒体任务路由与持久化。',
    category: 'canvas',
    level: 'intermediate',
    keywords: [
      '画布',
      'canvas',
      '节点',
      'asset',
      'task',
      'lineage',
      '影视',
      'storyboard',
      '360',
      '全景',
      'panorama',
      'equirectangular',
      '菜单',
    ],
    readTime: 12,
    updatedAt: '2026-06-29',
    icon: 'LayoutGrid',
    githubSource: 'docs/ai-infinite-canvas-mvp.md',
    relatedSlugs: ['media-providers', 'image-providers', 'canvas-video-workbench'],
  },
  {
    slug: 'media-providers',
    title: '多媒体 Provider',
    detail: '图片、语音、视频的统一能力注册与平台适配',
    description:
      'Spark Work 多媒体 Provider 配置：图片生成 / 编辑、语音合成 / 转写、视频生成 / 图生视频 / 视频编辑的统一能力注册表、平台适配器（APIMart / xAI / 火山 / 百炼 / 可灵 / Hailuo 等）。',
    category: 'provider',
    level: 'advanced',
    keywords: [
      'media',
      'provider',
      'apimart',
      'xai',
      'volcengine',
      'bailian',
      'kling',
      'spark_media',
    ],
    readTime: 14,
    updatedAt: '2026-06-29',
    icon: 'FileText',
    githubSource: 'docs/multimedia-model-providers.md',
    relatedSlugs: ['image-providers', 'canvas-mvp'],
  },
  {
    slug: 'image-providers',
    title: '图片生成 Provider',
    detail: 'spark_image MCP 与图片模型适配',
    description:
      'Spark Work 图片生成 Provider：图片 API 源与 imageApiType 字段、9 个内置图片预设、spark_image MCP 工具与 spark_media 统一栈的双链路判定、产物输出目录与 7 类渠道的参数归一规则。',
    category: 'provider',
    level: 'intermediate',
    keywords: ['image', '生图', 'imageProvider', 'spark_image', 'seedream', 'openai image'],
    readTime: 6,
    updatedAt: '2026-06-29',
    icon: 'ImageIcon',
    githubSource: 'docs/image-generation-providers.md',
    relatedSlugs: ['media-providers', 'canvas-mvp'],
  },
  {
    slug: 'web-search',
    title: '联网搜索',
    detail: 'spark_search MCP、免密链与 keyed 后端',
    description:
      'Spark Work 内置联网搜索 spark_search：web_search / fetch_url 工具、免密默认链（Bing / DuckDuckGo / 百度）、keyed 后端（博查 / Tavily / Serper）、配置项与降级策略。',
    category: 'mcp',
    level: 'beginner',
    keywords: ['搜索', 'web_search', 'fetch_url', 'Bing', 'DuckDuckGo', 'bocha', 'tavily', '联网'],
    readTime: 4,
    updatedAt: '2026-06-29',
    icon: 'Search',
    githubSource: 'docs/builtin-web-search.md',
    relatedSlugs: ['browser-automation', 'mcp-skills'],
  },
  {
    slug: 'browser-automation',
    title: '浏览器自动化',
    detail: 'Playwright MCP 与 spark_browser 可见窗口',
    description:
      'Spark Work 浏览器自动化：Playwright managed MCP 负责网页流程，spark_browser 内置 MCP 提供应用内可见窗口、本地 HTML 调试、console/network 和 profile 登录态。',
    category: 'mcp',
    level: 'intermediate',
    keywords: [
      'playwright',
      'browser',
      'spark_browser',
      'console',
      'network',
      'mcp__playwright',
      'browser_navigate',
    ],
    readTime: 6,
    updatedAt: '2026-07-05',
    icon: 'Globe',
    githubSource: 'docs/skills/browser-automation.md',
    relatedSlugs: ['web-search', 'mcp-skills'],
  },
  {
    slug: 'remote-connections',
    title: '远程连接',
    detail: 'Telegram / 飞书 桥接',
    description:
      'Spark Work 远程连接（Telegram / 飞书）：连接配置、配对流程、本地 webhook（127.0.0.1:32178）、内置命令（/help /sessions /models 等）、启动项集成。',
    category: 'governance',
    level: 'intermediate',
    keywords: ['remote', 'telegram', 'feishu', 'webhook', '/bind'],
    readTime: 9,
    updatedAt: '2026-06-29',
    icon: 'Cable',
    githubSource: 'docs/remote-connections.md',
    relatedSlugs: ['governance'],
  },
  {
    slug: 'auto-update',
    title: '自动更新',
    detail: 'GitHub Release + 官网版本中心 + UpdateService',
    description:
      'Spark Work 桌面端自动更新：electron-builder + GitHub Release + 官网版本中心（spark.yiqibyte.com）、UpdateService 检查/下载/安装状态、应用内更新入口、stable/beta 通道、Windows / macOS 签名构建。',
    category: 'release',
    level: 'intermediate',
    keywords: ['更新', 'update', 'release', 'electron-builder', 'WIN_CSC_LINK', 'CSC_LINK'],
    readTime: 8,
    updatedAt: '2026-06-29',
    icon: 'RefreshCw',
    githubSource: 'docs/github-release-auto-update.md',
    relatedSlugs: ['quick-start', 'desktop-guide'],
  },
  {
    slug: 'mcp-skills',
    title: 'MCP 与 Skills',
    detail: '可安装技能、加载策略与按需读取',
    description:
      'Spark Work MCP / Skills 体系：内置技能（apps/desktop/resources/skills）、可安装技能目录、自建安装源（artifact，默认路径）与 tarball / GitHub 回退三条安装路径、传输类型与字段校验、OAuth 授权、按需加载与运行时注入。',
    category: 'mcp',
    level: 'intermediate',
    keywords: [
      'skill',
      'SKILL.md',
      'installable',
      'artifact',
      'tarball',
      'OAuth',
      'spark_platform',
    ],
    readTime: 12,
    updatedAt: '2026-09-18',
    icon: 'PackageOpen',
    githubSource: 'docs/builtin-installable-skills.md',
    relatedSlugs: ['agents-workflows', 'browser-automation', 'web-search'],
  },
  {
    slug: 'governance',
    title: '权限与治理',
    detail: '审批、Rules、Hooks、用量账本与审计',
    description:
      'Spark Work 权限治理：会话权限模式与 Profile 规则的两层判定、审批卡四档与超时行为、Rules 作用域、经典 Hooks 与 Hooks V2、用量账本，以及当前真正可查的审计记录入口。',
    category: 'governance',
    level: 'advanced',
    keywords: ['权限', 'permission', '审批', 'approval', 'rules', 'hooks', '审计', '用量'],
    readTime: 14,
    updatedAt: '2026-09-18',
    icon: 'ShieldCheck',
    relatedSlugs: ['team-mode', 'remote-connections'],
  },
  {
    slug: 'desktop-guide',
    title: '桌面端架构',
    detail: 'Renderer / Main / IPC / 服务层与本地数据',
    description:
      'Spark Work 桌面端架构总览：Electron 主进程 / 渲染进程 / Preload / 类型化 IPC 桥、Agent Runtime 真实服务清单、本地 SQLite 与文件目录、凭据存储（keystore / 加密 vault）与三种执行引擎的载具差异。',
    category: 'getting-started',
    level: 'advanced',
    keywords: [
      'desktop',
      'electron',
      'renderer',
      'main',
      'IPC',
      'sqlite',
      'keytar',
      'credential vault',
    ],
    readTime: 16,
    updatedAt: '2026-09-18',
    icon: 'AppWindow',
    githubSource: 'docs/desktop-agent-development-guide.md',
    relatedSlugs: ['quick-start', 'code-development'],
  },
  {
    slug: 'builtin-tools',
    title: '内置工具',
    detail: '17 个内置 Skill 全览与挑选指南',
    description:
      'Spark Work 应用内置的全部 17 个 Skill 教程：claude-api / commit / react / frontend-design / skill-creator / multi-search-engine / browser-use / canvas-studio / multimedia-use / spark-web-tool / spark-workflow-generator / video-workflow / echarts / ui-ux-pro-max / spark-debug / find-skills / platform-manager。每条都给出真实技能 ID、触发场景、配套工具与跳过条件。',
    category: 'mcp',
    level: 'intermediate',
    keywords: [
      'Skill',
      'SKILL.md',
      '工具',
      '内置',
      'browser-use',
      'commit',
      'echarts',
      'spark-debug',
      'video-workflow',
      'spark-workflow-generator',
    ],
    readTime: 16,
    updatedAt: '2026-09-18',
    icon: 'PackageOpen',
    relatedSlugs: ['mcp-skills', 'browser-automation', 'web-search', 'agents-workflows'],
  },
  {
    slug: 'custom-tools',
    title: '自定义工具与工具包',
    detail: 'Tool Studio 与 Tool Package 两套体系',
    description:
      'Spark Work 自定义工具完整指南：Tool Studio 的 http / code / provider-vision 三种适配器与真实字段约束，以及 Tool Package 的 spark-tool.json manifest、五个 runtime.adapter、六条安装来源、受管工程 install/build、OS 行为与 Spark Capability 权限模型、密钥与启用卸载规则。附 11 个 custom_tools_* 与 22 个 tool_packages_* 工具清单和常见坑排查表。',
    category: 'mcp',
    level: 'advanced',
    keywords: [
      '自定义工具',
      '工具包',
      'Tool Studio',
      'Tool Package',
      'spark-tool.json',
      'custom_tools',
      'tool_packages',
      'secretRefs',
      'Keychain',
      'Spark Capability',
      'manifest',
    ],
    readTime: 20,
    updatedAt: '2026-09-19',
    icon: 'Boxes',
    relatedSlugs: ['builtin-tools', 'mcp-skills', 'agents-workflows', 'governance'],
  },
  {
    slug: 'connectors',
    title: '连接器',
    detail: '扩展中心的插件型连接器、四个内置运行时与 GitHub 两套实现',
    description:
      'Spark Work 连接器完整指南：先分清「连接器」在代码里的三种含义（扩展中心的插件型连接器、平台管理 MCP 的 github_* 工具、远程连接的 IM 机器人），再详述 plugin.json 完整字段与四类 contribution、source/trust 枚举、github / google / notion / obsidian 四个内置运行时的真实工具清单与能力开关、九个权限与「只有聚合闸门、无逐权限强制」的真实强制力、本地目录导入与默认不可用的市场、凭据只进系统 keystore、运行时的工具如何以 mcp__spark_plugins__<runtime>_<tool> 注入 Agent，以及 GitHub 两套实现的差异与 ConnectorsPanel 未被挂载这一界面缺口。附 20 行排查表。',
    category: 'mcp',
    level: 'advanced',
    keywords: [
      '连接器',
      '插件',
      'plugin.json',
      '连接器市场',
      '运行时',
      'runtime',
      'github',
      'github_',
      'mcp__spark_plugins__',
      'connector_accounts',
      'connector_connections',
      'allowWrites',
      'OAuth',
      'PKCE',
      'keystore',
      'credential_ref',
      '扩展中心',
    ],
    readTime: 20,
    updatedAt: '2026-09-19',
    icon: 'Cable',
    relatedSlugs: ['mcp-skills', 'builtin-tools', 'custom-tools', 'remote-connections'],
  },
  {
    slug: 'sub-apps',
    title: '子应用',
    detail: 'V1/V2 两种格式、五个展示面、生命周期与 spark_app 工具链',
    description:
      'Spark Work 子应用（Sub-App）完整指南：先分清 V1 单 HTML 与 V2 受管多文件的真实差异，再讲清五个展示面里只有 content / panel / overlay 真有宿主、17 个能力名与权限检查的真实位置、draft/published/archived 状态机（重点：归档在代码里不可逆）、发布对 enabled 的反向影响（V1 自动启用、V2 保持禁用）、版本号递增与「当前生效版本不能删」的保护、应用数据 512 KB 上限与 revision CAS、文件空间与 .sparkapp 分享包的十项导入检查、V2 后台服务与 release pinning 的持久任务，以及 39 个 spark_app_* 工具、19 个 developer_guide 查询主题与 17 条静态诊断。附 18 行排查表。',
    category: 'mcp',
    level: 'advanced',
    keywords: [
      '子应用',
      'sub-app',
      'Sub-App',
      '我的应用',
      'spark_app',
      '桌面宠物',
      'desktop-pet',
      '悬浮窗',
      'overlay',
      'global-window',
      '展示面',
      'surface',
      'spark-app.json',
      'V2 应用包',
      'draft_format',
      'publication_status',
      'archived',
      '归档',
      'spark_app_create',
      'spark-app-create',
      'sub_app_data',
      'sub_app_jobs',
      'sparkapp',
      '分享包',
      'CSP',
      'capability-asset',
    ],
    readTime: 22,
    updatedAt: '2026-09-19',
    icon: 'AppWindow',
    relatedSlugs: ['builtin-tools', 'mcp-skills', 'custom-tools', 'canvas-mvp'],
  },
  {
    slug: 'long-term-memory',
    title: '长期记忆',
    detail: '三层作用域、后台抽取、混合检索与整合进化',
    description:
      'Spark Work 三层长期记忆系统：User / Project / Agent 作用域隔离不串味，后台独立 LLM 抽取（与 OpenAI Memory、Mem0 同款架构）不干扰主对话，FTS5+sqlite-vec 混合检索，自动整合进化，search_memory / recall_memory 工具按需深挖。',
    category: 'mcp',
    level: 'intermediate',
    keywords: [
      '长期记忆',
      'memory',
      'search_memory',
      'recall_memory',
      'FTS5',
      'sqlite-vec',
      'Mem0',
      '记忆抽取',
      'scope',
    ],
    readTime: 6,
    updatedAt: '2026-07-04',
    icon: 'Boxes',
    relatedSlugs: ['builtin-tools', 'agents-workflows', 'mcp-skills'],
  },
  {
    slug: 'workflow-usage',
    title: '工作流编排',
    detail: '13 种节点、路由循环、完整编码流程与排错',
    description:
      'Spark Work 工作流（Workflow）完整教程：13 种节点作用与配置、outputKey 状态传递、条件路由、循环体子图可视化编辑、verify 失败语义，以及覆盖审批、并行子代理、Skill / Tool / MCP 审计和双交付物的编码功能任务示例。',
    category: 'team',
    level: 'intermediate',
    keywords: [
      '工作流',
      'workflow',
      '编排',
      'route',
      'loop',
      '循环节点',
      '路由判断',
      'outputKey',
      'workflow_run',
      '编码工作流',
      'verify',
      'approval',
    ],
    readTime: 24,
    updatedAt: '2026-07-22',
    icon: 'Boxes',
    relatedSlugs: ['agents-workflows', 'builtin-tools', 'governance'],
  },
  {
    slug: 'board-view',
    title: '任务面板',
    detail: '6 个状态列、拖拽、内联编辑与回收站',
    description:
      'Spark Work 任务面板（BoardView）使用教程：6 个状态列（todo / in-progress / bug-fix / done / accepted / closed）、TaskCard 完整字段（id / title / description / status / priority / assignee / project / tags / dueDate / processingAgent / acceptanceCriteria / testAgent / comments / attachments / sortOrder）、内联创建 / 编辑、拖拽改变状态、右键菜单、回收站软删除、多维筛选、通过 platform-manager Skill 让 Agent 自动操作。',
    category: 'governance',
    level: 'beginner',
    keywords: ['看板', 'board', '任务面板', 'kanban', 'todo', 'in-progress', 'accepted', '回收站'],
    readTime: 10,
    updatedAt: '2026-06-29',
    icon: 'FileText',
    relatedSlugs: ['team-mode', 'governance', 'builtin-tools'],
  },
  {
    slug: 'session-scheduled-tasks',
    title: '会话定时任务',
    detail: 'interval / cron / once 三类触发，会话级自动续接',
    description:
      'Spark Work 会话内定时任务：在单个会话作用域创建持久化任务，到点自动用本会话当时的 Agent/模型/权限/工作区续接一轮对话。支持 interval（固定间隔）/ cron（5 字段表达式）/ once（单次定时），用户工具栏和 Agent MCP 工具两个入口，调度引擎托管重试、并发与下次执行。',
    category: 'governance',
    level: 'intermediate',
    keywords: [
      '定时任务',
      'session_schedule',
      'cron',
      'interval',
      '轮询',
      '无人值守',
      '计划任务',
      'scheduled task',
    ],
    readTime: 6,
    updatedAt: '2026-08-10',
    icon: 'RefreshCw',
    relatedSlugs: ['agents-workflows', 'governance', 'builtin-tools'],
  },
  {
    slug: 'session-flow',
    title: '会话与消息流',
    detail: '轮次模型、排队与暂停、目标验收契约、计划审批、消息级操作、分叉与历史导入',
    description:
      'Spark Work 会话与消息流完整指南：先讲清「会话 → 轮次 → 事件」三层模型与 turnId 的作用，再展开消息流的真实链路（submit-turn 与 send-turn 的持久性差异、started 的真实语义、排队时消息气泡为何消失）、队列的两层结构与面板操作（含「拖拽排序重启后丢失」这个真实缺口）、出错暂停与两种恢复方式、调度并发（单会话 1 / 全局硬编码 6）。目标与计划部分覆盖 /goal 命令族、验收契约门控的解析规则（success_criteria 缺失即整块作废）、契约卡片、spark-goal-status 块的四种状态映射、五项预算熔断及其「计数依赖进度日志」的真实缺口、计划模式审批与闸门解除。会话级操作部分覆盖消息级操作（悬停栏按钮的真实出现条件、右键菜单、多选、乐观气泡状态机）、编辑最后一轮的先删后发语义、删除的按轮扩大与「浅清理」、会话分叉的轮次级锚点与元数据继承坑、参考会话的 10 条上限、代码还原点的 git 实现，以及历史导入的四个来源路径与四步流程。文末附 20 行排查表。',
    category: 'governance',
    level: 'advanced',
    keywords: [
      '会话',
      '消息流',
      '轮次',
      'turn',
      'turnId',
      '排队',
      '队列',
      'session:submit-turn',
      'session:send-turn',
      'turn_requests',
      '队列暂停',
      'SessionQueuePauseState',
      '目标模式',
      'Goal',
      '验收契约',
      'pending_contract',
      'spark-goal-contract',
      'spark-goal-status',
      '计划模式',
      'plan_proposed',
      '计划审批',
      '消息级操作',
      '编辑消息',
      '删除消息',
      'rewind-last-turn',
      '分叉',
      '复制会话',
      'session_lineage',
      '参考会话',
      '代码还原点',
      'checkpoint',
      '历史导入',
      'HistoryImport',
      '乐观消息',
    ],
    readTime: 24,
    updatedAt: '2026-09-19',
    icon: 'TerminalSquare',
    relatedSlugs: [
      'quick-start',
      'governance',
      'session-scheduled-tasks',
      'long-term-memory',
      'agents-workflows',
    ],
  },
  {
    slug: 'canvas-video-workbench',
    title: '视频工作台',
    detail: '深度视频转换、关键帧提取与一站式剪辑',
    description:
      'Spark Work 画布视频工作台：视频节点的全屏一站式处理台，覆盖深度视频转换（本地 Depth Anything V2，离线不上云）、关键帧提取（scene / iframe / uniform 三策略，超限自动退化，可回填画布）、剪辑处理（转码、切割、音频分离、变速、倒放、画面裁剪）和多段时间线轨道拼接。',
    category: 'canvas',
    level: 'intermediate',
    keywords: [
      '视频工作台',
      '深度视频转换',
      'Depth Anything',
      '关键帧',
      'keyframe',
      '视频剪辑',
      'video workbench',
      'video_depth_map',
    ],
    readTime: 7,
    updatedAt: '2026-08-10',
    icon: 'LayoutGrid',
    relatedSlugs: ['canvas-mvp', 'media-providers', 'image-providers'],
  },
  {
    slug: 'computer-use',
    title: '电脑操作',
    detail: 'Computer Use 权限、原子动作、委派任务与原生宿主',
    description:
      'Spark Work 电脑操作（Computer Use）完整指南：Agent 直接操作真实桌面的能力。先讲清两条架构完全不同的使用路径——原子动作（会话模型自己逐步操作，每个会话一个隐式会话、空闲 5 分钟释放）与委派的 start_task（独立决策循环，各自的任务契约预算不同），再展开权限模型：会话权限层里 fail-closed 的 computer_direct_action / computer_unknown 硬闸，与生产路径上更早生效的自动放行名单的关系，以及 Broker 层「策略只做风险分级、不做内容拦截」的真实边界（evaluate 在所有分支返回 allow，唯一 deny 是 focus_mismatch；任务契约里 allowedApps / allowedDomains / forbiddenActions 等字段没有任何读取点）。执行内核部分覆盖 L0–L4 风险计算与哪些升级规则在生产不可达、十个原子工具与 click 的语义改写、坐标按「模型看到的图」换算、type_text 带 into/submit 会拆成最多三个动作、五个控制工具的真实语义（pause 与 takeover 逐行等价、resume 只有 MCP 路径会重启算子、bind_target 必须先暂停）。底层部分覆盖原生宿主为什么必需、双向签名校验与本地信任旁路、5 字节帧头 stdio 协议与「没有请求级取消，超时即 SIGKILL 宿主」、心跳与每会话一次的重启预算、元素树渲染与 treeVersion 的 stale 语义、以及 macOS 与 Windows 的能力不对等。数据部分覆盖三套尺寸的截图、AES-256-GCM 加密快照库与保留策略（只有证据帧有 24 小时 TTL、整体无磁盘配额）、预览令牌的 5 分钟 TTL 与 turn 边界撤销、17 项凭据类应用黑名单的实际覆盖面。最后是界面可达性（设置页只有授权与诊断、那套设置没有界面、全新安装不会武装紧急停止键）与 10 个 V2 开关里哪 4 个没有任何消费者。文末附 30 行排查表。',
    category: 'governance',
    level: 'advanced',
    keywords: [
      '电脑操作',
      'Computer Use',
      'computer-use',
      'spark_computer',
      '原生宿主',
      'Native Host',
      'SparkComputerHost',
      '原子动作',
      'start_task',
      'click',
      'type_text',
      'invoke_element',
      'bind_target',
      'takeover',
      'kill switch',
      '紧急停止',
      'screen_permission_denied',
      'accessibility_permission_denied',
      'stale_tree',
      'stale_frame',
      'focus_mismatch',
      'action_noop',
      'ComputerPolicyService',
      'ComputerControlBroker',
      'ComputerApprovalService',
      '快照',
      'snapshot vault',
      'sensitive_input_blocked',
      'computer_sessions',
      'V2 开关',
    ],
    readTime: 26,
    updatedAt: '2026-09-19',
    icon: 'AppWindow',
    relatedSlugs: ['governance', 'mcp-skills', 'builtin-tools', 'sub-apps', 'code-development'],
  },
  {
    slug: 'optional-capabilities',
    title: '可选功能组件',
    detail: '两条安装通道、四个完整性服务与按需下载的可选资源',
    description:
      'Spark Work 可选功能组件完整指南：Codex 本地运行环境、离线 Office 预览、本地深度处理、FFmpeg、Chromium 与语音输入资源六个大体积组件不随安装包分发，而是按需下载。本页先讲清 definitions.ts 里 archive 与 external 两条安装通道的真实差异——四个 external 能力里三个照样从 Spark 自建制品仓库下载，只有 Chromium 走 npm 生态，selectArtifacts 返回空数组只是「不走通用流水线」的意思；接着逐个拆解四个专用完整性服务的探测与安装：FFmpeg 的 managed/system/none 三级降级与从目录名解析版本、Chromium 的四组包解析候选与三级浏览器探测及其 150 MB 固定估值、语音包的三组件与四值平台白名单及单飞保护、Codex 运行时的四段目录与 bundled 开发态旁路。版本协商部分给出协议基线 0.144.5、exact-sdk-match 与 newest-compatible 的取舍、五种失败原因对应的用户提示原文，以及三个环境变量的注入点。archive 部分覆盖七个阶段、包内 manifest 与全量文件 SHA-256、三层路径与符号链接防护、CapabilityPackageHealth 实际只覆盖两个能力的事实，以及激活失败时「原版本已保留」的回滚语义。操作语义部分说明 install/update/repair 是同一个实现（修复必然整包重下）、取消与卸载只对 archive 能力可用、卸载只删状态目录而够不到外部能力的二进制、自动更新默认值与 check 的触发条件、启动提醒的 7 天冷却与按版本静音，以及清单缓存 24 小时内不联网会让 remoteAvailable 为假从而静默跳过提醒的关键坑。协议部分覆盖 capability-asset:// 的五步路径穿越与符号链接防护、四条 host 分支与构建期资源外部化插件的 fail-fast，以及 Codex Runtime 诊断卡片的指标、四个告警阈值与「只回收空闲实例」的重启语义。文末附 11 个 IPC 通道契约、30 行排查表，以及 11 项声明了但当前不起作用的东西。',
    category: 'getting-started',
    level: 'advanced',
    keywords: [
      '可选功能组件',
      'optional-capabilities',
      '按需安装',
      '完整性',
      'Codex 本地运行环境',
      'codex-runtime',
      '离线 Office 预览',
      'office-viewer',
      '本地深度处理',
      'local-depth',
      'FFmpeg',
      'ffmpeg',
      'Chromium',
      'chromium',
      '语音输入资源',
      'voice-pack',
      'OptionalCapabilityManager',
      'capability-asset',
      'active.json',
      'manifest-cache',
      'remoteAvailable',
      '启动提醒',
      '自动更新',
      '卸载',
      '修复',
      '组件损坏',
      'Codex Runtime 诊断',
      'codex-runtime:diagnostics',
    ],
    readTime: 24,
    updatedAt: '2026-09-19',
    icon: 'PackageOpen',
    relatedSlugs: [
      'desktop-guide',
      'auto-update',
      'browser-automation',
      'canvas-video-workbench',
      'governance',
    ],
  },

  {
    slug: 'credentials-and-secrets',
    title: '凭据与密钥',
    detail: '四种落点、ref 规则与明文边界',
    description:
      'SparkWork 凭据与密钥管理完整指南：密钥实际有四种落点（共享 keystore 的 macOS 集中 vault、第二个 keytar 实现 TokenStore、SQLite app_settings 明文、CLI 的 credentials.json），逐层讲清各自的读写路径与保护边界。覆盖 keystore 的常量与五个 API、critical 的 legacyChecked 惰性迁移与 deleteSecret 语义、keystore_ref 列清单与 tool_package_config 的 DB 级互斥约束、ref 命名规则总表、两份同名 maskSecret 的差异、Provider 凭据从表单到真实请求的全链路（空串写库的语义坑、provider:get-api-key 的明文回显与受管 Provider 硬拒、导出会把明文 Key 写盘、测试连接会真的发请求）、平台账号与 MCP OAuth 的 TokenStore 细节（含备份文件被两个命名空间共用导致取消 MCP 授权会删掉登录备份）、三处明文落点（IM 机器人凭据还会明文回显到普通输入框、会话与项目环境变量、MCP config_json）、声明与填值分离的三条面（自定义工具 secretRefs 全生命周期、工具包 secret 环境变量与一次性安全输入、子应用连接槽）、脱敏覆盖面、删除与清理边界、备份导出与账号同步各路径的密钥行为，附 24 行排查表与事实边界。',
    category: 'governance',
    level: 'advanced',
    keywords: [
      '凭据',
      '密钥',
      'keychain',
      'keytar',
      'keystore',
      'safeStorage',
      'credential vault',
      'API Key',
      'secretRefs',
      'app_settings',
      'credentials.json',
      'TokenStore',
      '脱敏',
      '明文',
      'SPARK_AUTH_KEYTAR_SERVICE',
      'tool-package secret',
    ],
    readTime: 24,
    updatedAt: '2026-09-19',
    icon: 'KeyRound',
    relatedSlugs: ['governance', 'mcp-skills', 'custom-tools', 'desktop-guide'],
  },
  {
    slug: 'data-and-backup',
    title: '本地数据与备份',
    detail: '数据落点、升级恢复点与账号同步',
    description:
      'SparkWork 本地数据、备份与账号同步完整指南：先把数据分成三个根讲清——应用数据在 {userData}（开发实例走兄弟目录 @spark/desktop-dev，由 SPARK_DATA_PROFILE 控制）、跨工作区记忆与看板在 ~/.spark-agent、Spark CLI 另用 ~/.spark。再讲唯一权威存储 spark.db（WAL 与 pragma、101 个迁移与 schema_migrations）与升级安全网：迁移前自动恢复点走 SQLite 在线备份产出单文件快照，保留 2 份 / 14 天，自动回滚的唯一门槛是 createdThisStartup === true；同一个 backups/database 目录下还有继承安装版数据时裸拷的 pre-inherit-* 三件套，它不受任何清理约束，且整个 backups/ 不计入存储用量、也没有界面清理入口。最后讲账号同步：7 个类别默认全关、只在点「立即同步」时执行、走同一个 /desktop-sync/execute 端点（预览靠 mode 区分），四重校验（字段白名单、键名黑名单、类型表、值文本扫描）是整条跳过而非裁剪，配保护列表防止云端覆盖本地。含保留期对照、真实限额、本地应用顺序、25 行排查表，并如实记录两处代码与文案不一致。',
    category: 'governance',
    level: 'advanced',
    keywords: [
      '本地数据',
      '备份',
      '恢复点',
      '账号同步',
      'SPARK_DATA_PROFILE',
      'userData',
      'spark.db',
      'WAL',
      'migration',
      'pre-migration',
      'pre-inherit',
      'desktop-sync',
      '冲突',
      '保护列表',
      'sync-policy',
      '保留策略',
    ],
    readTime: 26,
    updatedAt: '2026-09-19',
    icon: 'Database',
    relatedSlugs: ['credentials-and-secrets', 'governance', 'desktop-guide', 'auto-update'],
  },
  {
    slug: 'hooks-v2',
    title: 'Hooks V2 实操手册',
    detail: '生命周期事件、条件与映射、作用域授权、执行与重试',
    description:
      'SparkWork Hooks V2 完整实操手册：先辨析产品里三套同名机制——桌面 Hooks V2（7 个生命周期事件、通知/提示音/调用工具三种动作）、设置页底部的经典通知（V1 四个节点、布尔开关），以及 spark-engine 里那套没有任何界面的 shell 命令 hook（4 个闭集事件，退出码 2 或输出 block 决策可真正拦截，桌面 Spark 执行器同样会加载项目目录下的 .spark/settings.json）。再讲清 Hooks V2 的真实行为：七个事件的发射时机与 payload、确定性事件 ID 与两级去重、条件路径白名单与八个操作符的真实语义（eq 比较 null 恒为 false、contains 不支持数组）、三种值表达式与模板占位符规则、作用域优先级与基于执行哈希的绑定授权、什么改动会让授权失效、事件到执行的四段管线与三个定时器、超时/重试/幂等/并发的准确语义，以及 20 行排查对照。含如实记录的已知缺口：high-write 工具无法开放、条件无法通过界面移除、失败事件不清理、部分协议能力界面配不到。',
    category: 'governance',
    level: 'advanced',
    keywords: [
      'Hooks',
      'Hook',
      'hooks-v2',
      '生命周期事件',
      'turn.completed',
      'permission.requested',
      'response.committed',
      '执行哈希',
      'executionHash',
      '作用域绑定',
      'needs_review',
      '输入映射',
      '条件表达式',
      '幂等键',
      '重试策略',
      'serial_per_session',
      'hook_events',
      'hook_runs',
      '经典通知',
      'shell hooks',
    ],
    readTime: 24,
    updatedAt: '2026-09-19',
    icon: 'Webhook',
    relatedSlugs: ['governance', 'agents-workflows', 'data-and-backup', 'credentials-and-secrets'],
  },
  {
    slug: 'spark-cli',
    title: 'Spark CLI 与桌面联动',
    detail: '终端入口、命令面、TUI、本地桥与 ~/.spark 数据模型',
    description:
      'Spark CLI（包名 @spark/agent，命令 spark）完整参考：18 个子命令与参数解析的真实边界（所有 flag 共用一张解析表，与本命令无关的 flag 会被静默忽略）、三种输出格式的区别（--json 给事件流、--output-format json 才给一行结果对象）、完整退出码表（取消是 130、用法错误是 2、update 有专属 0/1/2/3/4）、会话账本的组织方式与 -c/-r 的差别、TUI 的七个准入条件与 9 条公开斜杠命令、图片附件的格式与限额。桌面联动部分讲清本地回环桥的发现与选主、bridge 描述文件协议、三个真实端点、哪些渠道会被桥接（只有 Anthropic 与显式标记 responses 的 OpenAI 渠道），以及桥的安全模型与凭据链路。最后是 ~/.spark 与项目级 .spark 的数据落点、配置分层合并规则、各子命令的真实行为与 28 行排查对照。',
    category: 'governance',
    level: 'advanced',
    keywords: [
      'Spark CLI',
      'spark',
      '@spark/agent',
      'spark-engine',
      'TUI',
      '命令行',
      '终端',
      'spark install',
      'spark update',
      'spark doctor',
      'spark login',
      'spark models',
      'spark mcp',
      'spark memory',
      'spark plan',
      'spark skills',
      'spark todo',
      'spark sessions',
      'output-format',
      'stream-json',
      '退出码',
      'exit code',
      '会话账本',
      'events.jsonl',
      '本地桥',
      'bridge',
      'sparkwork',
      'hosts/sparkwork',
      '桌面联动',
      'codexApiKind',
      'SPARK_HOME',
      'SPARK_AGENT_HOME',
      'credentials.json',
      'update.lock',
    ],
    readTime: 26,
    updatedAt: '2026-09-19',
    icon: 'Terminal',
    relatedSlugs: ['quick-start', 'credentials-and-secrets', 'data-and-backup', 'hooks-v2'],
  },
]

export const categoryLabels: Record<DocCategory, string> = {
  'getting-started': '入门',
  code: '代码开发',
  team: '团队 Agent',
  canvas: '无限画布',
  content: '内容与媒体生产',
  provider: 'Provider',
  mcp: 'MCP & 工具',
  governance: '治理',
  release: '发布',
}

export const categoryOrder: DocCategory[] = [
  'getting-started',
  'code',
  'team',
  'canvas',
  'provider',
  'mcp',
  'governance',
  'release',
]

export function findDocsTopic(slug: string): DocsTopicMeta | undefined {
  return docsTopics.find((t) => t.slug === slug)
}

export function docsTopicsByCategory(category: DocCategory): DocsTopicMeta[] {
  return docsTopics.filter((t) => t.category === category)
}

export function relatedDocsTopics(slug: string): DocsTopicMeta[] {
  const t = findDocsTopic(slug)
  if (!t?.relatedSlugs?.length) return []
  return t.relatedSlugs.map((s) => findDocsTopic(s)).filter((x): x is DocsTopicMeta => Boolean(x))
}
