const Database = require('better-sqlite3');
const db = new Database('C:/Users/Administrator/AppData/Roaming/@spark/desktop/spark.db', { readonly: true });
const agents = db.prepare("SELECT id, name, description, built_in, enabled, is_default, agent_adapter, permission_mode, reasoning_effort, workflow_id, prompt, skill_ids_json, metadata_json FROM agents").all();
console.log('AGENTS_JSON_START');
console.log(JSON.stringify(agents, null, 2));
console.log('AGENTS_JSON_END');
const wfs = db.prepare("SELECT id, scope, name, version, description, status, enabled, graph_json, tags_json FROM workflows").all();
console.log('WORKFLOWS_JSON_START');
console.log(JSON.stringify(wfs, null, 2));
console.log('WORKFLOWS_JSON_END');
