const Database = require('better-sqlite3');
const fs = require('fs');
const db = new Database('C:/Users/Administrator/AppData/Roaming/@spark/desktop/spark-dev.db', { readonly: true });
const a = db.prepare("SELECT id, name, description, built_in, enabled, is_default, provider_profile_id, model_id, agent_adapter, permission_mode, reasoning_effort, workflow_id, rule_ids_json, hook_config_json, metadata_json, length(prompt) AS prompt_len, length(skill_ids_json) AS sk_len, length(disabled_skill_ids_json) AS dsk_len, length(mcp_server_ids_json) AS mcp_len FROM agents WHERE id = ?").get('93785cf1-d570-4a2a-8919-108fbf7f39c3');
console.log(JSON.stringify(a, null, 2));
const skills = db.prepare("SELECT skill_ids_json FROM agents WHERE id = ?").get('93785cf1-d570-4a2a-8919-108fbf7f39c3');
fs.writeFileSync('G:/spark/spark-agent/.spark-artifacts/skill_ids.json', skills.skill_ids_json, 'utf8');
const mcp = db.prepare("SELECT mcp_server_ids_json FROM agents WHERE id = ?").get('93785cf1-d570-4a2a-8919-108fbf7f39c3');
fs.writeFileSync('G:/spark/spark-agent/.spark-artifacts/mcp_ids.json', mcp.mcp_server_ids_json, 'utf8');
const prompt = db.prepare("SELECT prompt FROM agents WHERE id = ?").get('93785cf1-d570-4a2a-8919-108fbf7f39c3');
fs.writeFileSync('G:/spark/spark-agent/.spark-artifacts/agent_prompt.txt', prompt.prompt, 'utf8');
const disabled = db.prepare("SELECT disabled_skill_ids_json FROM agents WHERE id = ?").get('93785cf1-d570-4a2a-8919-108fbf7f39c3');
fs.writeFileSync('G:/spark/spark-agent/.spark-artifacts/disabled_skills.json', disabled.disabled_skill_ids_json, 'utf8');
db.close();
